spring.application.name=SpringBoot_RestAPI_CRUD_Operations

#spring.datasource.url=jdbc:mysql://localhost:3306/employeedatabase
#spring.datasource.name=root
#spring.datasource.password=Swap25


spring.datasource.username=root
spring.datasource.password=Swap25
spring.datasource.url=jdbc:mysql://localhost:3306/employeedatabase
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true