package com.it;

import java.util.Optional;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import com.it.entity.Account;
import com.it.entity.AccountPK;
import com.it.repository.AccountRepository;

@SpringBootApplication
public class Application {

    private final AccountRepository accountRepository;

    Application(AccountRepository accountRepository) {
        this.accountRepository = accountRepository;
    }

	public static void main(String[] args) {
		ConfigurableApplicationContext context = SpringApplication.run(Application.class, args);
		
		AccountRepository accountRepo = context.getBean(AccountRepository.class);
	/*
		AccountPK pk=new AccountPK();
		pk.setAccId(2);
		pk.setAccType("Current");
		pk.setAccNum(3123245l);
		
		Account acc=new Account();
		acc.setHolderName("Raju");
		acc.setBranch("Ameerpet");
		acc.setAccountPk(pk);
		accountRepo.save(acc);
		*/
		
		AccountPK pk=new AccountPK();
		pk.setAccId(2);
		pk.setAccType("Current");
		pk.setAccNum(3123245l);
		
		Optional<Account> findById = accountRepo.findById(pk);
		findById.ifPresent(System.out::println);
		
		/*
		Below is explanation for above configuring.
		AccountPK is your composite primary key class.
		Account is the entity class that uses @EmbeddedId or @IdClass.
		accountRepo.findById(pk) triggers a query like:
		
		SELECT * FROM account 
		WHERE (acc_id, acc_num, acc_type) = (?, ?, ?)
		which is generated by Spring Data JPA using Hibernate. 
		 
		 */
	}

}

/*
// inserting
Hibernate: select a1_0.acc_id,a1_0.acc_num,a1_0.acc_type,a1_0.branch,a1_0.holder_name from account a1_0 where (a1_0.acc_id,a1_0.acc_num,a1_0.acc_type) in ((?,?,?))
Hibernate: insert into account (branch,holder_name,acc_id,acc_num,acc_type) values (?,?,?,?,?)

// fetching
Hibernate: select a1_0.acc_id,a1_0.acc_num,a1_0.acc_type,a1_0.branch,a1_0.holder_name from account a1_0 where (a1_0.acc_id,a1_0.acc_num,a1_0.acc_type) in ((?,?,?))
Account [holderName=Raju, branch=Ameerpet, accountPk=AccountPK [accId=2, accType=Current, accNum=3123245]]


*/