spring.application.name=22-Web_MVC_JSP_App-45


# View Resolver configuration
# we need to configure View Resolver because it will tell you where the view files are available in our appl
# prefix is nothing but the location where our View files are available
spring.mvc.view.prefix=/views/
# suffix is nothing but extensions of our view file
spring.mvc.view.suffix=.jsp