spring.application.name=16-SpringDataJPA-H2_App

# Data JPA is managing the connections
# datasource : to establish connection with the database
spring.datasource.username=h2db
spring.datasource.password=Swap25
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
# it is used to show sql query on console
spring.jpa.show-sql=true 
spring.h2.console.enabled=true   
spring.h2.console.path=h2-console
server.port=7788
