spring.application.name=19-Student_Management_App45

spring.datasource.url=jdbc:mysql://localhost:3306/sbms45
spring.datasource.username=root
spring.datasource.password=Swap25

#ORM properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# sending email via SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=swapnilkature917@gmail.com
spring.mail.password=kyft wpgu ynrv kftf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true