spring.application.name=08-Data_JPA_App45

# Data Source properties
spring.datasource.username=root
spring.datasource.password=Swap25
spring.datasource.url=jdbc:mysql://localhost:3306/sbms45


#ORM properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update