spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbms27
    username: root
    password: Swap25
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
     hibernate:
#     if a table is available drop it and create new one.
#      ddl-auto: create
#     when tables are already created & we just want to update it then use update. 
      ddl-auto: update
     show-sql: true
