spring.application.name=22-Web_MVC_JSPApp

# we need to configure View Resolver because it will tell you where the view files are available in our appl
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp